# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsJta8Rfpx1H6iIqaPzxspDLfpq9Sqcu
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import pickle

# 1. Simulasi Data Antropometri & Klinis Balita
np.random.seed(42)
n_samples = 1000

data = {
    'Age_Months': np.random.randint(6, 60, n_samples),
    'Gender': np.random.choice([0, 1], n_samples), # 0: Female, 1: Male
    'Height_cm': np.random.uniform(60, 110, n_samples),
    'Weight_kg': np.random.uniform(5, 20, n_samples),
    'Birth_Weight_kg': np.random.uniform(2.0, 4.0, n_samples),
    'Exclusive_Breastfeeding': np.random.choice([0, 1], n_samples), # 0: No, 1: Yes
}

df = pd.DataFrame(data)

# 2. Logika Sederhana Indikator Stunting (Penetapan Label Risiko)
# Menggunakan rasio perkiraan Tinggi/Umur
df['Stunting_Risk'] = np.where(df['Height_cm'] / df['Age_Months'] < 1.4, 1, 0)

# 3. Melatih Model Machine Learning (Random Forest)
X = df.drop('Stunting_Risk', axis=1)
y = df['Stunting_Risk']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 4. Simpan Model AI ke file .pkl
with open('stunting_model.pkl', 'wb') as file:
    pickle.dump(model, file)

print("Model AI berhasil dilatih dan disimpan sebagai 'stunting_model.pkl'!")